### ISSUE TITLE
jfx:native goal does not respect jfxMainAppJarName

### ISSUE THREAD

**Issue by ctrueden** [javafx-maven-plugin/javafx-maven-plugin#128]
Steps to reproduce:

1.  Generate a sample project:

    ```
$ mvn archetype:generate -DinteractiveMode=false -DarchetypeGroupId=com.zenjava \
        -DarchetypeArtifactId=javafx-basic-archetype -DarchetypeVersion=2.0.1 \
        -DgroupId=foo -DartifactId=bar -Dversion=0.1.0-SNAPSHOT -DorganizationName=Org
    ```

2.  Replace the generated `javafx-maven-plugin` configuration with:

    ```xml
            <plugin>
                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.1.2</version>
                <configuration>
                    <mainClass>foo.MainApp</mainClass>
                    <jfxMainAppJarName>Fubar</jfxMainAppJarName>
                </configuration>
            </plugin>
    ```

3. Remove the line `<finalName>bar</finalName>`

4.  Try to build:

    ```
$ mvn jfx:native
...
[INFO] --- javafx-maven-plugin:8.1.2:native (default-cli) @ bar ---
[INFO] Building Native Installers
/Users/curtis/t/bar/target/jfx/app/lib
/Users/curtis/t/bar/target/jfx/app/lib/commons-lang-2.6.jar
/Users/curtis/t/bar/target/jfx/app/lib/jcl-over-slf4j-1.6.1.jar
/Users/curtis/t/bar/target/jfx/app/lib/log4j-1.2.16.jar
/Users/curtis/t/bar/target/jfx/app/lib/miglayout-core-4.2.jar
/Users/curtis/t/bar/target/jfx/app/lib/miglayout-javafx-4.2.jar
/Users/curtis/t/bar/target/jfx/app/lib/slf4j-api-1.6.1.jar
/Users/curtis/t/bar/target/jfx/app/lib/slf4j-log4j12-1.6.1.jar
[INFO] Skipping Mac Application Image because of configuration error Main application jar is missing.
Advice to Fix: Make sure to use fx:jar task to create main application jar.
[INFO] Skipping DMG Installer because of configuration error Main application jar is missing.
Advice to Fix: Make sure to use fx:jar task to create main application jar.
[INFO] Skipping PKG Installer because of configuration error Main application jar is missing.
Advice to Fix: Make sure to use fx:jar task to create main application jar.
[INFO] Skipping Mac App Store Ready Bundler because of configuration error Main application jar is missing.
Advice to Fix: Make sure to use fx:jar task to create main application jar.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
    ```

5.  App is present, but self-contained application is missing:

    ```
$ ls -R target/jfx
app/

target/jfx/app:
Fubar.jar  lib/

target/jfx/app/lib:
commons-lang-2.6.jar      jcl-over-slf4j-1.6.1.jar  log4j-1.2.16.jar          miglayout-core-4.2.jar    miglayout-javafx-4.2.jar  slf4j-api-1.6.1.jar       slf4j-log4j12-1.6.1.jar
    ```

Is this a bug, or am I doing something wrong in the configuration?

**Comment by maxd** [comment]
Reproduced. Add `.jar` extension to fix problem:

    <jfxMainAppJarName>Fubar.jar</jfxMainAppJarName>

**Comment by ctrueden** [comment]
Thanks @maxd. Adding the `.jar` suffix does result in generation of the self-contained application. However, I do still see warnings like:
```
  Using default package resource [volume icon]  (add package/macosx/imagej-2.0.0-rc-31-SNAPSHOT-volume.icns to the class path to customize)
```
I.e.: for a `jfxMainAppJarName` of `ImageJ` I put a file `src/main/deploy/package/macosx/ImageJ.icns` and it doesn't pick it up, presumably because it's using the default artifactId-version finalName?

Symptom of the same issue? Or shall I file a separate issue?

**Comment by FibreFoX** [comment]
Hi @ctrueden,

I think this is no bug, just missing documentation (domain-transfer of zenjava.com takes a bit longer than expected).

Could you try to use this kind of configuration?

```
        <plugin>
            <groupId>com.zenjava</groupId>
            <artifactId>javafx-maven-plugin</artifactId>
            <version>8.1.2</version>
            <configuration>
                <mainClass>foo.MainApp</mainClass>
                <jfxMainAppJarName>Fubar</jfxMainAppJarName>
                <verbose>true</verbose>
            </configuration>
        </plugin>
```

Having ```<verbose>``` set to ```true``` should show you what file got picked. When you want to override these files, please use the same filename as they are required by underlying packager.

**Comment by ctrueden** [comment]
@FibreFoX Thanks, I understand that the filename needs to match. See my comment above—the icon file it wants _is_ mentioned: `package/macosx/imagej-2.0.0-rc-31-SNAPSHOT-volume.icns`. However, in that case I had `jfxMainAppJarName` set to `ImageJ`.

The fact that the version string is part of the filename is a no-go because you'd have to rename the file every time you change the POM version. (And your release tooling would need to know to do this, too...)

I'm fairly confident there is still a legitimate bug lurking here relating to `jfxMainAppJarName`. When using the Ant tasks, setting the `fx:application` element `name` attribute uses that name across the board, both for `fx:jar` and `fx:deploy`, as long as those two tasks each declare `<fx:application refid="YourAppID"/>` to reference that same `fx:application`.

**Comment by FibreFoX** [comment]
@ctrueden thanks, I will investigate. I personally don't have access to any macos-running device, maybe it's a fluke within java-packager. Just for being sure: what version of java do you use? (Reminder to myself: for bug-reports we need java- and plugin-versions)

**Comment by ctrueden** [comment]
@FibreFoX I am on Java 1.8.0_45.

So on Windows and/or Linux, when you follow my recipe above, it works as expected? You get a self-contained application generated?

I did accidentally leave one thing out of my recipe: the `<finalName>` line must be removed from the generated POM as well. Sorry for that!

I tried to dig into the `javafx-maven-plugin` code to fix the issue, but I got confused by the major terminology differences between the Maven, Ant and Java packager API. It looks like the Maven plugin calls the Java packager API, but mapping the Ant tasks' behavior onto that is pretty challenging. For example, as I described above, in the Ant tasks, you have to explicitly tell the `fx:jar` and `fx:deploy` tasks about the correct `fx:application` element which declares the `name` you want. I see that the `JarMojo` does call:
```java
createJarParams.setOutfile(jfxMainAppJarName);
```
But nowhere in the `NativeMojo` could I find anything referencing the `jfxMainAppJarName`, an application object of any kind, or really anything that would lead me to believe the `NativeMojo` could possibly infer which app name is desired for packaging into the self-contained app. I guess it could just read it from the file system, but... it would make more sense to me if there were an API call for it like everything else.

**Comment by FibreFoX** [comment]
Just for being curious, did you try current master-branch? We fixed several issues, maybe it's already fixed with other changes? I'll report back if I found something ;) and I WILL find something.

**Comment by ctrueden** [comment]
@FibreFoX Interesting. On master, the behavior is different. Better, but still not as I would expect:
```
$ ls target/jfx/*
target/jfx/app:
ImageJ.jar  lib/

target/jfx/native:
imagej-2.0.0-rc-31-SNAPSHOT-1.0.dmg  imagej-2.0.0-rc-31-SNAPSHOT-1.0.pkg  imagej-2.0.0-rc-31-SNAPSHOT.app/
```

So self-contained applications are being built, but `jfx:native` is still not picking up on the `jfxMainAppJarName` as hoped. (And hence the right icon is not chosen, etc.)

**Comment by FibreFoX** [comment]
Just for being sure: ```jfxMainAppJarName``` is for setting the name of generated ```-jfx.jar```, not the native bundle itself. It has to end with ```.jar```, because otherwise we don't have valid executable or the bundler would refuse to work here.

As it seems, we might have different problems/bugs here:
1. missing icon (probably due to filename)
2. ```jfxMainAppJarName``` not being respected?!

**Comment by FibreFoX** [comment]
Hi @ctrueden , can you show me what is printed as app-name?
https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/mac/MacDmgBundler.java#L66

This should be reported when having verbose as ```true```

**Comment by FibreFoX** [comment]
Hi @ctrueden , it fiddled a bit with the javafx-branch of your project. You are setting finalName, this is used as appName, to override this, please use the corresponding configuration-entry ```<appName>```.

Something like this should end up as your configuration:
```xml
<plugin>
    <groupId>com.zenjava</groupId>
    <artifactId>javafx-maven-plugin</artifactId>
    <version>8.1.2</version>
    <configuration>
        <identifier>ImageJ</identifier>
        <mainClass>${main-class}</mainClass>
        <verbose>true</verbose>
        <jfxMainAppJarName>ImageJ.jar</jfxMainAppJarName>
        <appName>ImageJ</appName>
        <bundleArguments>
            <runtime/>
        </bundleArguments>
    </configuration>
</plugin>
```

**Comment by ctrueden** [comment]
Thanks for your time investigating this, @FibreFoX. I truly appreciate it.

> You are setting finalName

True, but we only set it in profiles which are not active here. So I do not think that is the issue. In any case, the minimal project I describe above from the archetype also has the issue, without setting `finalName`.

To be clear, all I am looking for here is a way to set the name of the project, such that the version string is not required in any filenames in the working copy. This is certainly doable from Ant, so I would expect should be possible from Maven as well.

@hinerm and I are doing some testing on Windows and Linux now, and will report back if we notice any platform-specific issues here in any direction.

In the short term, we're going to use `maven-antrun-plugin` to get the job done. When we have a spare hour or two, we'll try to dig into this matter further and maybe submit a PR if we figure it out.

**Comment by ctrueden** [comment]
Just noticed your comments about `<appName>`. We weren't setting that. Trying now!

**Comment by ctrueden** [comment]
:fireworks: Setting the `<appName>` does the trick! So much back and forth for such a small thing... thanks for your patience!
