### ISSUE TITLE
Error executing native windows app

### ISSUE THREAD

**Issue by arthurcvm** [javafx-maven-plugin/javafx-maven-plugin#252]
Hi! I have a problem with the .exe installer, when I launch the application the system return "Failed to launch JVM" and others library errors, is in others PCs, because in my machine is all ok, i don't make idea how to solve, because search in the web and I found nothing that fits to solve, my POM is below:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>br.com.siscomtech</groupId>
    <artifactId>SISCOMTECH</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>

    <name>SISCOMTECH</name>
    
    <developers>
        <developer>
            <name>Arthur Cezar</name>
            <email>arthurcvm@hotmail.com</email>
            <url>https://www.siscomtech.com.br</url>
        </developer>
    </developers>
    
    <organization>
        <name>SisComTech</name>
    </organization>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <mainClass>Classes.Main</mainClass>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.7.0</version>
                <configuration>
                   <appName>SISCOMTECH Ótica</appName>
                    <title>SISCOMTECH Ótica</title>
                    <verbose>true</verbose>
                    <needShortcut>true</needShortcut>
                    <needMenu>true</needMenu>
                    <bundleArguments>
                        <icon.ico>src/main/resources/img/favicon.ico</icon.ico>
                        <runtime />
                    </bundleArguments>                    
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    
    <repositories>
        <repository>
            <name>Repositorio Autocom SnapShot</name>
            <id>Snapshot</id>
            <url>http://www.autocomsistemas.com.br:8081/nexus/content/repositories/autocom/</url>
        </repository>
    </repositories>
    
    <dependencies>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.6</version>
        </dependency>
        <dependency>
            <groupId>br.com.samuelweb</groupId>
            <artifactId>java-nfe</artifactId>
            <version>3.10.5</version>
        </dependency>
        
        <dependency>
            <groupId>net.sf.jasperreports</groupId>
            <artifactId>jasperreports</artifactId>
            <version>6.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>org.hsqldb</groupId>
            <artifactId>hsqldb</artifactId>
            <version>2.3.4</version>
        </dependency>
    </dependencies>

</project>
```

**Comment by FibreFoX** [comment]
Hi there,

unfortunately this has nothing todo with the javafx-maven-plugin itself, but I do know why it is failing! You have set the plugin to not include some JRE inside the bundle.

I found the source of the problem on stackoverflow with two different topics:
[JavaFX DEB Bundle Without JRE Doesn't Work](http://stackoverflow.com/a/40126355/1961102)
[JavaFX Application does not start when JAVA_HOME is set](http://stackoverflow.com/a/40059467/1961102)

The real problem here is that Oracle did NOT document how the generic native launcher does JRE-detection. You are required to have some JRE installed and windows-registry keys set at location `HKLM\Software\JavaSoft\Java Runtime Environment\[CurrentVersion]\JavaHome`.

Does this help you to find your solution?

**Comment by arthurcvm** [comment]
Oh, nice! I remember when the deploy is in JavaFX project with native bundle the construct command include the JRE in the packet to avoid this error, I will look the suggestion and return a reply in the end of day.

Thanks!

**Comment by FibreFoX** [comment]
```xml
                    <bundleArguments>
                        <icon.ico>src/main/resources/img/favicon.ico</icon.ico>
                        <runtime /> <!-- this removes the JRE -->
                    </bundleArguments> 
```
Maybe you want to remove this `<runtim />`-part or you copy-pasted the wrong part ;) I hope this missing-JRE thing is the real problem.

**Comment by arthurcvm** [comment]
Is based in [POM exemple](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/master/src/it/03-cli-jfx-native/pom.xml), but I really was wrong, I look others and have a idea in build with [package jar](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/master/src/it/09-withPackagerJar/pom.xml) or [native launcher](https://github.com/javafx-maven-plugin/javafx-maven-plugin/blob/master/src/it/19-native-launcher-configuration-windows-workaround167/pom.xml).

**Comment by FibreFoX** [comment]
What happens if you remove the `<runtime />`-part? Does it work?

**Comment by arthurcvm** [comment]
Hi, look my POM remake:

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>br.com.siscomtech</groupId>
    <artifactId>SISCOMTECH</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>

    <name>SISCOMTECH</name>
    
    <developers>
        <developer>
            <name>Arthur Cezar</name>
            <email>arthurcvm@hotmail.com</email>
            <url>https://www.siscomtech.com.br</url>
        </developer>
    </developers>
    
    <organization>
        <name>SisComTech</name>
    </organization>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <mainClass>InterfaceGrafica.MainApp</mainClass>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.7.0</version>
                <configuration>
                   <appName>SISCOMTECH Ótica</appName>
                    <title>SISCOMTECH Ótica</title>
                    <verbose>true</verbose>
                    <needShortcut>true</needShortcut>
                    <needMenu>true</needMenu>
                    <bundleArguments>
                        <icon.ico>src/main/resources/img/favicon.ico</icon.ico>
                    </bundleArguments>                    
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    
    <repositories>
        <repository>
            <name>Repositorio Autocom SnapShot</name>
            <id>Snapshot</id>
            <url>http://www.autocomsistemas.com.br:8081/nexus/content/repositories/autocom/</url>
        </repository>
    </repositories>
    
    <dependencies>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.6</version>
        </dependency>
        <dependency>
            <groupId>br.com.samuelweb</groupId>
            <artifactId>java-nfe</artifactId>
            <version>3.10.5</version>
        </dependency>
        
        <dependency>
            <groupId>net.sf.jasperreports</groupId>
            <artifactId>jasperreports</artifactId>
            <version>6.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>org.hsqldb</groupId>
            <artifactId>hsqldb</artifactId>
            <version>2.3.4</version>
        </dependency>
    </dependencies>

</project>
`
I launch the command: 

> mvn clean jfx:native

and make the clean install in other PC, but the JVM error persistis, look the images:

![Print 1](https://cloud.githubusercontent.com/assets/9640276/21509227/338e976a-cc6e-11e6-839e-db2e59d21f43.png)

![Print 2](https://cloud.githubusercontent.com/assets/9640276/21509235/415c76e6-cc6e-11e6-9ae6-01b010c60a53.png)

![Print 3](https://cloud.githubusercontent.com/assets/9640276/21509238/472ea4fe-cc6e-11e6-801b-98c78288de63.png)

**Comment by FibreFoX** [comment]
Can you choose some more simple appName? That field is not intended for real names, this is more the resulting filename.

Would be nice to have some small project where I can reproduce this locally (from source, not from the binary).

**Comment by arthurcvm** [comment]
My new POM:

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>br.com.siscomtech</groupId>
    <artifactId>SISCOMTECH</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>

    <name>SISCOMTECH</name>
    
    <developers>
        <developer>
            <name>Arthur Cezar</name>
            <email>arthurcvm@hotmail.com</email>
            <url>https://www.siscomtech.com.br</url>
        </developer>
    </developers>
    
    <organization>
        <name>SisComTech</name>
    </organization>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <mainClass>Classes.Main</mainClass>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>com.zenjava</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>8.7.0</version>
                <configuration>
                   <appName>SISCOMTECH</appName>
                    <title>SISCOMTECH</title>
                    <verbose>true</verbose>
                    <needShortcut>true</needShortcut>
                    <needMenu>true</needMenu>
                    <bundleArguments>
                        <icon.ico>src/main/resources/img/favicon.ico</icon.ico>
                        <runtime />
                    </bundleArguments>                    
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    
    <repositories>
        <repository>
            <name>Repositorio Autocom SnapShot</name>
            <id>Snapshot</id>
            <url>http://www.autocomsistemas.com.br:8081/nexus/content/repositories/autocom/</url>
        </repository>
    </repositories>
    
    <dependencies>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.6</version>
        </dependency>
        <dependency>
            <groupId>br.com.samuelweb</groupId>
            <artifactId>java-nfe</artifactId>
            <version>3.10.5</version>
        </dependency>
        
        <dependency>
            <groupId>net.sf.jasperreports</groupId>
            <artifactId>jasperreports</artifactId>
            <version>6.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>org.hsqldb</groupId>
            <artifactId>hsqldb</artifactId>
            <version>2.3.4</version>
        </dependency>
    </dependencies>

</project>`

but the error persist, about the project access I'm send a invitation to your GitHub profile email, to access the repository.

**Comment by FibreFoX** [comment]
Hi there, I have pushed some changes into that repository, please check if they work for you.

To summarize:
- `<appName>` should not contain non-ascii chars
- the wrong main-class was provided
- keep the files below "src/main/deploy/" in sync with `<appName>`

**Comment by arthurcvm** [comment]
I solve this! After your commit the error persist, but I install the JRE 64bit with the offline installer and configure the JAVA_HOME to it, the app is launch, but my doubt is about the JRE don't include in the app packet...

**Comment by FibreFoX** [comment]
I might rephrase myself, but you need to remove the `<runtime />`-part if you want to include the JRE.

https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/252#issuecomment-269320165

**Comment by FibreFoX** [comment]
@arthurcvm is this issue now solved for you? I would like to close this issue :)

**Comment by arthurcvm** [comment]
Thanks! Solve this removing the > <runtime /> but the program no launch in 32bits OS, what I solve this?

**Comment by FibreFoX** [comment]
You are required to run the build-script for each targeted system/architecture, that means you are required to run maven on 32bit windows for creating 32bit windows installers, and for creating 64bit installers you are required to run maven on 64bit windows system. This is a [documented restriction of the javapackager itself](https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html#JSDPG586)
